### PR TITLE
Add surefire to integration tests

### LINKED ISSUE #10: Fix testing on projects that use the plugin
More specifically, maven-surefire-plugin breaks and must be disabled when reactive-app-maven-plugin is used.

e.g. maven surefire (blocking Lagom team testing)

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #10

### CODE REVIEW

**Comment by dwijnand** [comment]
How does this fix "Failed to create assembly for docker image  (with mode 'dir'): Error creating assembly archive docker: You must set at least one file.. If you include the build artifact please ensure that you have built the artifact before with 'mvn package' (should be available in the target/ dir). Please see the documentation (section "Assembly") for more information. [Error creating assembly archive docker: You must set at least one file.]"?

**Comment by dwijnand** [comment]
Are you testing with `mvn install`?

**Comment by eed3si9n** [comment]
> Are you testing with mvn install?

Yeah, bin/run-integration-tests.sh includes mvn install.

```
$ export GPG_TTY=$(tty)
$ bin/run-integration-tests
```

See https://gist.github.com/eed3si9n/f5aec6564cdba786e5885d3c1953fcb6 for the full output.

```
....
[INFO] --- maven-install-plugin:2.4:install (default-install) @ reactive-app-maven-plugin ---
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/target/reactive-app-maven-plugin-0.3.1-SNAPSHOT.jar to /Users/eed3si9n/.m2/repository/com/lightbend/rp/reactive-app-maven-plugin/0.3.1-SNAPSHOT/reactive-app-maven-plugin-0.3.1-SNAPSHOT.jar
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/pom.xml to /Users/eed3si9n/.m2/repository/com/lightbend/rp/reactive-app-maven-plugin/0.3.1-SNAPSHOT/reactive-app-maven-plugin-0.3.1-SNAPSHOT.pom
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/target/reactive-app-maven-plugin-0.3.1-SNAPSHOT.jar.asc to /Users/eed3si9n/.m2/repository/com/lightbend/rp/reactive-app-maven-plugin/0.3.1-SNAPSHOT/reactive-app-maven-plugin-0.3.1-SNAPSHOT.jar.asc
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/target/reactive-app-maven-plugin-0.3.1-SNAPSHOT.pom.asc to /Users/eed3si9n/.m2/repository/com/lightbend/rp/reactive-app-maven-plugin/0.3.1-SNAPSHOT/reactive-app-maven-plugin-0.3.1-SNAPSHOT.pom.asc
....

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.lightbend.rp.test.lagomendpoints.impl.HelloServiceTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.766 s - in com.lightbend.rp.test.lagomendpoints.impl.HelloServiceTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hello-impl ---
[INFO] Building jar: /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/src/it/lagom-endpoints/hello-impl/target/hello-impl-1.0.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hello-impl ---
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/src/it/lagom-endpoints/hello-impl/target/hello-impl-1.0.jar to /Users/eed3si9n/.m2/repository/com/lightbend/rp/test/lagomendpoints/hello-impl/1.0/hello-impl-1.0.jar
[INFO] Installing /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/src/it/lagom-endpoints/hello-impl/pom.xml to /Users/eed3si9n/.m2/repository/com/lightbend/rp/test/lagomendpoints/hello-impl/1.0/hello-impl-1.0.pom
[INFO]
[INFO] --- reactive-app-maven-plugin:0.3.1-SNAPSHOT:build (build-docker) @ hello-impl ---
[INFO] App type: Lagom
[INFO] App name: hello-impl
[INFO] App version: 1.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Copying files to /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/src/it/lagom-endpoints/hello-impl/target/docker/hello-impl/1.0/build/maven
[INFO] Building tar: /Users/eed3si9n/work/orchestration/reactive-app-maven-plugin/src/it/lagom-endpoints/hello-impl/target/docker/hello-impl/1.0/tmp/docker-build.tar
[INFO] DOCKER> [hello-impl:1.0] "rp-hello-impl": Created docker-build.tar in 1 second
[INFO] DOCKER> [hello-impl:1.0] "rp-hello-impl": Built image sha256:51511
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] hello .............................................. SUCCESS [  1.371 s]
[INFO] hello-api .......................................... SUCCESS [  1.847 s]
[INFO] hello-impl ......................................... SUCCESS [ 18.323 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.481 s
[INFO] Finished at: 2018-07-20T09:02:46-04:00
[INFO] Final Memory: 48M/620M
[INFO] ------------------------------------------------------------------------
Generating K8s resources for hello-impl:1.0 and applying with kubectl
```

**Comment by eed3si9n** [comment]
I didn't run into "Failed to create assembly for docker image."

```
$ mvn -version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T03:58:13-04:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"
```

**Comment by dwijnand** [comment]
So you can no longer reproduce https://github.com/lightbend/reactive-app-maven-plugin/issues/10#issuecomment-402917750 ?

**Comment by eed3si9n** [comment]
Or it got fixed by https://github.com/lightbend/reactive-app-maven-plugin/commit/a0d852a8ad084cea64f77aaf1ae4b4e246b8e5ac?

**Comment by dwijnand** [comment]
Your PR predates that commit.

Oh whatever, the changes are good (and always were). Maybe #10 has just gone away now, or maybe it'll resurface down the line. Let's merge this, which will close the issue.

**Pull request merged**
